<div style="display:flex; justify-content:center; align-items:center; position:relative;">

  <h2 style="margin:auto; text-align:center;">
    UNIVERSIDAD TÉCNICA DEL NORTE <br>
    Facultad de Ingeniería en Ciencias Aplicadas - FICA
  </h2>

  <img src="https://wstemproject.eu/files/2019/06/logo-UTN-2017-768x768.png"
       width="100px">
</div>

<h4 style="text-align:center;"> CARRERA DE CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL </h4>

<h4 style="text-align:center;"> PROGRAMACIÓN II </h4>

<h4 style="text-align:center;"> Librerías para Ciencia de Datos  </h4>

<h5 style="text-align:right;"> Docente: Ing. Wilson Pérez </h5>
<h5 style="text-align:right;"> Marzo - Septiembre 2026</h5>

Las librerías de Python para ciencia de datos son herramientas que facilitan todo el proceso: desde la manipulación de datos hasta el modelado con inteligencia artificial.

Python destaca justamente por su ecosistema enorme (aproximadamente 200,000 librerías) orientado a análisis, visualización y machine learning

 <div style="text-align:center">
    <img src="https://github.com/wilsonperezrc/varios/blob/main/img/img.p.1.4.1.png?raw=true" alt="Descripción" width="600">
</div>

***
### 1. NumPy
***

NumPy (**Numerical Python**) es la columna vertebral de todo el ecosistema de datos en Python.

Problema:

In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]

resultado = []
for i in range(len(a)):
    resultado.append(a[i] + b[i])

¿Se puede hacer esto más rápido y con menos código?

Las listas de Python son potentes porque pueden guardar cualquier tipo de dato (objetos), pero eso las hace lentas, debido a que cada elemento en una lista de Python es un objeto completo con metadatos.

In [ ]:
[1, 4, "Hola", 9, "mundo", [2, 5], True]

NumPy introduce el *n-dimensional* array, donde todos los elementos deben ser del mismo tipo () y se almacenan físicamente uno al lado del otro en la RAM, permitiendo que el procesador acceda a ellos a una mayor velocidad.

#### 1.1. Utilizando numpy

In [2]:
import numpy as np

In [3]:
# Desde lista
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [15]:
# Matriz de ceros (3 filas, 4 columnas)

b2 = [[0, 0, 0, 0],
 [0., 0., 0., 0.],
 [0., 0., 0., 0.]]

In [16]:
b2[1][1] = 5
print(b2)

[[0, 0, 0, 0], [0.0, 5, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]


In [17]:
b2[1][1] = 'a'
print(b2)

[[0, 0, 0, 0], [0.0, 'a', 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]


In [18]:
# Matriz de ceros (3 filas, 4 columnas)
b = np.zeros((3, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
b[1][1] = 5
print(b)

[[0. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# resultado?????
b[1][1] = 'a'

In [20]:
# Matriz de unos
c = np.ones((2, 2))
print(c)

[[1. 1.]
 [1. 1.]]


In [21]:
# 5 números equiespaciados entre 0 y 10
d = np.linspace(0, 10, 5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
# Rango con paso (0, 2, 4...)
e = np.arange(0, 20, 2)
print(e)

[ 0  2  4  6  8 10 12 14 16 18]


In [24]:
# Matriz aleatoria (Mersenne Twister)
f = np.random.rand(3, 3)
print(f)

[[0.04918538 0.77082757 0.32655667]
 [0.78054857 0.17474946 0.84372177]
 [0.38213074 0.69524293 0.0261605 ]]


In [79]:
import time

# Crear 1 millón de elementos
size = 1000000
lista = list(range(size))
array = np.arange(size)

# Tiempo en Lista de Python
inicio = time.time()
lista_resultado = [x * 2 for x in lista]
print(f"Lista Python: {time.time() - inicio:.5f} segundos")

# Tiempo en NumPy
inicio = time.time()
array_resultado = array * 2
print(f"NumPy Array: {time.time() - inicio:.5f} segundos")

Lista Python: 0.02588 segundos
NumPy Array: 0.00136 segundos


#### 1.2. Atributos

In [26]:
f = np.random.rand(3, 3)
print(f)

[[0.47053707 0.67146359 0.51580247]
 [0.68311861 0.40715169 0.82992994]
 [0.93925753 0.26293556 0.95468504]]


In [27]:
# Dimensiones
f.shape

(3, 3)

In [31]:
# Número de dimensiones
f.ndim

2

In [30]:
a = np.array([1, 2, 3])
print(a)

a.ndim

[1 2 3]


1

In [34]:
# Tipo de dato (muy importante para el consumo de memoria)
f.dtype

dtype('float64')

In [35]:
a.dtype

dtype('int64')

In [37]:
# Número total de elementos
f.size

9

#### 1.3. Vectorización

NumPy en lugar de procesar elementos uno por uno con bucles, delega la operación a bibliotecas de bajo nivel

##### Ejemplo 1

In [40]:
precios = [100, 200, 300, 400]
con_impuesto = []
for p in precios:
    con_impuesto.append(p * 1.10)

print(con_impuesto)

[110.00000000000001, 220.00000000000003, 330.0, 440.00000000000006]


In [41]:
precios = np.array([100, 200, 300, 400])
con_impuesto = precios * 1.10
print(con_impuesto)

[110. 220. 330. 440.]


In [42]:
precios2 = [100, 200, 300, 400]

In [51]:
precios2 * 2

[100, 200, 300, 400, 100, 200, 300, 400]

##### Ejemplo 2

In [53]:
angulos = np.array([0, np.pi/2, np.pi])
resultados = np.sin(angulos)
print(resultados)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


##### Ejemplo 3: Producto Punto

In [54]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
resultado = np.dot(a, b)
print(resultado)

32


In [55]:
a = [1, 2, 3]
b = [4, 5, 6]
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]

print(dot)

32


#### 1.4. Operaciones

##### Ejemplo 4:

In [56]:
# Comparaciones lógicas
notas = np.array([4.5, 7.8, 9.2, 5.0, 3.2])
resultados = notas >= 7.0
print(resultados)

[False  True  True False False]


In [57]:
# Operaciones estadísticas

resultados = np.mean(notas)
print(resultados)

5.9399999999999995


In [58]:
resultados = np.median(notas)
print(resultados)

5.0


In [59]:
resultados = np.std(notas)
print(resultados)

2.215942237514326


In [68]:
resultados = np.sum(notas)
print(resultados)

29.7


In [73]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [74]:
escalar = 10
print(matriz + escalar)

[[11 12 13]
 [14 15 16]]


In [75]:
# Operaciones por ejes
print(np.sum(matriz, axis=0)) # Suma las columnas
print(np.sum(matriz, axis=1)) # Suma las filas

[5 7 9]
[ 6 15]


<div style="text-align:center">
    <img src="https://github.com/wilsonperezrc/varios/blob/main/img/img.p.1.4.2.png?raw=true" alt="Descripción" width="800">
</div>

<div style="text-align:center">
    <img src="https://github.com/wilsonperezrc/varios/blob/main/img/img.p.1.4.3.png?raw=true" alt="Descripción" width="800">
</div>

#### 1.4. Ejemplos

In [65]:
presion = np.array([101.3, 102.5, 900.0, 101.8, 288.5, 103.0])

# 1. Crear una lista para valores menores a 200
mascara = presion < 200
print(mascara)

[ True  True False  True False  True]


In [66]:
# 2. Aplicar
datos_limpios = presion[mascara]
print(datos_limpios)

[101.3 102.5 101.8 103. ]


In [67]:
# 3. Reemplazar mayores a 200 por el promedio de los sanos
promedio = np.mean(datos_limpios)
presion[presion > 200] = promedio

print(f"Datos corregidos: {presion}")

Datos corregidos: [101.3  102.5  102.15 101.8  102.15 103.  ]


***
### Ejercicios

##### Ejercicio 1: Crea un array con los números del 1 al 10



##### Ejercicio 2: Operaciones básicas

Dado a y b, sumar y multiplícar ambos arrays elemento a elemento

In [80]:
a = [1, 2, 3]
b = [4, 5, 6]

##### Ejercicio 3: Estadística básica

Dado a, calcula la media, mediana, y la desviación estándar

In [ ]:
a = [10, 20, 30, 40, 50]

##### Ejercicio 4: Array de ceros y unos

- Crea un array de 5 ceros
- Crea un array de 5 unos

##### Ejercicio 5: Obtén solo los valores mayores a 10

In [ ]:
a = [1, 5, 10, 15, 20]

##### Ejercicio 6: Máximo y mínimo

In [ ]:
[3, 7, 2, 9, 1]

##### Ejercicio 7: Sumar por filas

In [ ]:
[[1,2,3],
 [4,5,6]]

##### Ejercicio 8: Reemplazo

Reemplaza los valores mayores a 10 por 0.

In [ ]:
[5, 10, 15, 20]

##### Ejercicio 9: Suma b a todos los elementos de a

In [81]:
a = [1,2,3]
b = 5

##### Ejercicio 10:

Cuenta cuántos valores son mayores que la media


In [ ]:
a = [10, 20, 30, 40, 50]

##### Ejercicio 11:

Simula notas de estudiantes:

- Genera 50 notas entre 0 y 10
- Calcula promedio
- Determina cuántos aprueban (>=7)

In [5]:
import numpy as np


In [6]:

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [7]:

print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [12]:
print(a[1,1])

4
